name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Production Release
        if: ${{ !contains(github.ref_name, '.b') }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            docs/update-site/eclipse/rdi8.0/Server/RPGUNIT.SAVF
            docs/files/iRPGUnit for RDi 9.5.1.3+.pdf
            docs/files/rdi8.0/iRPGUnit*.zip

      - name: Create Beta Release
        if: ${{ contains(github.ref_name, '.b') }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            docs/beta-version/update-site/eclipse/rdi8.0/Server/RPGUNIT.SAVF
            docs/beta-version/files/iRPGUnit for RDi 9.5.1.3+.pdf
            docs/beta-version/files/rdi8.0/iRPGUnit*.zip
          prerelease: true