name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Production Release
        if: ${{ !contains(github.ref_name, '.b') }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: docs/update-site/eclipse/rdi8.0/Server/RPGUNIT.SAVF

      - name: Create Beta Release
        if: ${{ contains(github.ref_name, '.b') }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: docs/beta-version/update-site/eclipse/rdi8.0/Server/RPGUNIT.SAVF